### PR TITLE
enabling no-code setup and fixing codes starting w/0

### PR DESCRIPTION
**Pull request by cantupaz**

### CODE REVIEW

**Comment by cantupaz** [comment]
BTW. this PR probably fixes https://github.com/guerrerotook/securitas-direct-new-api/issues/153 and https://github.com/guerrerotook/securitas-direct-new-api/issues/149 (if I understood their problem) and some random errors I was seeing where the code is trying to access a property of a string...

**Comment by cantupaz** [comment]
I merged all the changes that separate the api from the HA integration. It's been working for a couple of days with no errors and fixes the API changes that Securitas introduced in the new year.

What needs some testing is that I made a couple of changes to the actual API calls because I couldn't arm or disarm my alarm completely. Instead of DARM1, this version is sending DARM1DARMPERI1.  And instead of ARM1, I'm sending ARM1PERI1. If that causes problems, I have an idea on how to fix them.

**Review by guerrerotook — APPROVED** [review]

**Comment by guerrerotook** [comment]
@cantupaz I will let you that you merge it when you like it, from there I will create a new release!

**Comment by cantupaz** [comment]
I merged. Thanks for the access. I'm happy to help with this as long as I have a Securitas alarm.

Could you test air quality sensors? I don't have those in my installation and I have no way of testing.

It would also be good to test the arming and disarming, since I changed the codes sent to Securitas

**Comment by guerrerotook** [comment]
> I merged. Thanks for the access. I'm happy to help with this as long as I have a Securitas alarm.
> 
> Could you test air quality sensors? I don't have those in my installation and I have no way of testing.
> 
> It would also be good to test the arming and disarming, since I changed the codes sent to Securitas

I'm going to test this on my installation to see how it goes and then I will release a new version. Happy to communicate with you using telegram or WhatsApp if you prefer it.

**Comment by lukelalo** [comment]
Sorry, but this piece of code is right?

**Comment by guerrerotook** [comment]
Hi @lukelalo what do you mean by that? Can you elaborate? That was a rename of a typo I think.

**Comment by lukelalo** [comment]
Yes, the CONF_INSTALLATION_KEY was renamed, but the "instalation" value assigned wasn't (line 51). 

I mean that if the code is using devices.insta**ll**ation, shouldn't the CONF_INSTALLATION_KEY value be "insta**ll**ation" with double l instead of "insta**l**ation"?

Regards
Pablo García

**Comment by cantupaz** [comment]
I agree that the value of the CONF_INSTALLATION_KEY should be installation, but I decided against changing it because it would break the existing configs of users that are using this integration. Maybe something to change later. Is something not working as you'd expect?

**Pull request merged**
