### PR TITLE
Initialize protom_response

### PR DESCRIPTION
**Pull request by cantupaz**
I somehow missed initializing the attribute that holds the protom_response. This causes problems: https://github.com/guerrerotook/securitas-direct-new-api/issues/205

I also cleaned up a couple of minor things

### CODE REVIEW

**Review by garybrowngeo — APPROVED** [review]
This looks good. Should fix the protom_reponse error being reported

**Review by guerrerotook — APPROVED** [review]

**Comment by guerrerotook** [comment]
@cantupaz approved, thanks very much! In the future tag me as a reviewer of the PR and I will get a notification! After this I will publish a new version.

**Comment by cantupaz** [comment]
I missed tagging you! Thanks for approving.

**Comment by garybrowngeo** [comment]
No problem. You did all the work! Thanks for sorting!

**Pull request merged**
