### PR TITLE
api: manager: fix JSON error checks

### PR DESCRIPTION
**Pull request by Noltari**
Correctly checks JSON for errors key.

### CODE REVIEW

**Comment by guerrerotook** [comment]
Hey, thanks for the PR.

**Comment by guerrerotook** [comment]
@Noltari I tried you changed in the official repository for Home Assistant, where I'm developing these changes and the linter show a lot of errors for your PR,

homeassistant/components/securitas_direct/__init__.py:116: error: Incompatible return value type (got "None", expected "CheckAlarmStatus")  [return-value]
homeassistant/components/securitas_direct/__init__.py:122: error: Incompatible return value type (got "None", expected "CheckAlarmStatus")  [return-value]
homeassistant/components/securitas_direct/__init__.py:127: error: Incompatible return value type (got "None", expected "CheckAlarmStatus")  [return-value]

So I'm going to revert your changes because I want the code to be compliant with the home assistant definitions.

**Comment by Noltari** [comment]
> @Noltari I tried you changed in the official repository for Home Assistant, where I'm developing these changes and the linter show a lot of errors for your PR,
> 
> homeassistant/components/securitas_direct/**init**.py:116: error: Incompatible return value type (got "None", expected "CheckAlarmStatus") [return-value] homeassistant/components/securitas_direct/**init**.py:122: error: Incompatible return value type (got "None", expected "CheckAlarmStatus") [return-value] homeassistant/components/securitas_direct/**init**.py:127: error: Incompatible return value type (got "None", expected "CheckAlarmStatus") [return-value]
> 
> So I'm going to revert your changes because I want the code to be compliant with the home assistant definitions.

Looks like you are only testing my changes to apimanager.py, but you aren't testing the changes I did to init.py...

**Comment by guerrerotook** [comment]
In init.py is the same.

I'm developing the code in this repo, https://github.com/guerrerotook/home-assistant/tree/securitas_direct/homeassistant/components/securitas_direct, inside the dev container that has all the requirements and I can test in the latest version of the code. If you can test you changes there with the git hooks that would be fantastic.

**Comment by Noltari** [comment]
> In init.py is the same.
> 
> I'm developing the code in this repo, https://github.com/guerrerotook/home-assistant/tree/securitas_direct/homeassistant/components/securitas_direct, inside the dev container that has all the requirements and I can test in the latest version of the code. If you can test you changes there with the git hooks that would be fantastic.

Well, that doesn't make sense, since according to your log the first exception happens on line 116 (which is the old version of __init__.py) instead of line 118, which is the new version of __init__.py:
```
homeassistant/components/securitas_direct/init.py:116: error: Incompatible return value type (got "None", expected "CheckAlarmStatus") [return-value]

```
https://github.com/guerrerotook/securitas-direct-new-api/pull/10/files#diff-1b667864416fe20cf73344c2a190fed6c72eac0bd3da1afca94463ab2ff790daR115

**Comment by Noltari** [comment]
> In init.py is the same.
> 
> I'm developing the code in this repo, https://github.com/guerrerotook/home-assistant/tree/securitas_direct/homeassistant/components/securitas_direct, inside the dev container that has all the requirements and I can test in the latest version of the code. If you can test you changes there with the git hooks that would be fantastic.

I'm still investigating this, but it will take me a while, so maybe it's better if you revert my changes.
However, my changes try to fix bad error handling all over the source code, which should be addressed at some point if the changes are reverted...

**Pull request merged**
